---
- hosts: all
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  - name: Disable selinux permanently
    lineinfile:
      path: /etc/selinux/config
      regex: "^SELINUX="
      line: "SELINUX=permissive"

  - name: Disable selinux before reboot
    shell: setenforce 0
